Double quote to prevent globbing and word splitting.

diff --git a/bin/generate b/bin/generate
--- a/bin/generate
+++ b/bin/generate
@@ -9,7 +9,7 @@
 CURRENT_DIR=$(pwd)
 
 cleanup() {
-    cd ${CURRENT_DIR} || exit
+    cd "${CURRENT_DIR}" || exit
     echo "Don't forget to publish on Github, NPM and dart registries."
 }
 
@@ -22,8 +22,8 @@ echo
 
 ### Javascript generation of @keyclic/sdk-javascript ###
 echo "Javasript es6 generation."
-rm -rf ${CURRENT_DIR}/javascript-es6 2>&1
-mkdir ${CURRENT_DIR}/javascript-es6
+rm -rf "${CURRENT_DIR}"/javascript-es6 2>&1
+mkdir "${CURRENT_DIR}"/javascript-es6
 docker run \
     --rm \
     --volume ${PWD}:/local \
@@ -38,7 +38,7 @@ docker run \
 
 #### Dart generation of keyclic_sdk_api ###
 echo "Dart generation."
-rm -rf ${CURRENT_DIR}/dart 2>&1
+rm -rf "${CURRENT_DIR}"/dart 2>&1
 docker run \
     --rm \
     --volume ${PWD}:/local \
@@ -54,14 +54,14 @@ docker run \
 sleep 10
 
 # Prepare and build package for javascript-es6
-cd ${CURRENT_DIR}/javascript-es6 || { echo -e "Cannot find javascript-es6 directory"; exit 1; }
+cd "${CURRENT_DIR}"/javascript-es6 || { echo -e "Cannot find javascript-es6 directory"; exit 1; }
 
 npm install
 npm run build
 npm run prettier
 
 # Prepare and build package for dart
-cd ${CURRENT_DIR}/dart || { echo -e "Cannot find dart directory"; exit 1; }
+cd "${CURRENT_DIR}"/dart || { echo -e "Cannot find dart directory"; exit 1; }
 
 # remove bracket in function parameter name
 sed -i -r 's/([a-zA-Z]+)\[([a-zA-Z]*)\]/\1_\2_/g' lib/api/*
